### ISSUE TITLE
Change shipping_options (json) to shipping_option (string) everywhere

### ISSUE THREAD

**Issue by gregplaysguitar** [sonsandco/django-shoptools#23]

**Comment by pbright** [comment]
I ended up changing this to an int (stores shipping_option id). Take a look at Soohyang and let me know what you think.

**Comment by gregplaysguitar** [comment]
I think it should be a string, because shipping options won't always be a django model. You might need to add a unique slug to your Option model?

The other advantage is that the slug will be meaningful when viewing the json, whereas an integer isn't

**Comment by pbright** [comment]
Sounds good.
